{% set version = "3.6.1" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: aa50b0143df7c89ce91be020fe41382613a817354b33acdc6641b44f8ced3828
  patches:
    - omit-local-site-packages.patch  # [osx]
    - osx64-dist.patch                # [osx and x86_64]
    - win-find_exe.patch              # [win]
    - win-library_bin.patch           # [win]
    # Adjust FD_SETSIZE to allow select() to wait on more connections
    # simultaneously.  Desirable for serious use of Tornado on Windows.
    # See also:
    # - https://bugs.python.org/issue28708
    # - https://github.com/zeromq/libzmq/issues/1165
    - fd_setsize.patch                # [win]
    - mingw-w64--DMS_WINXX.patch
    - win-msc_ver-1900.patch
    - fix-ABI-issue29943.patch
    # - https://bugs.python.org/issue22724 (rebased to 3.6.1 and autoreconf'ed)
    - py_build_environ_3.patch

build:
  number: 4
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.6     # [unix]
  track_features:
    - vc14              # [win]
  script_env:
    - python_branding

requirements:
  host:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 7.*      # [unix]
    - sqlite 3.16.*     # [unix]
    - tk 8.6.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 6.0*      # [linux]
    - libffi 3.2.*      # [unix]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - pkg-config
  run:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 7.*      # [unix]
    - sqlite 3.16.*     # [unix]
    - tk 8.6.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 6.0*      # [linux]
    - libffi 3.2.*      # [unix]
    - vs2015_runtime    # [win]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: 'General purpose programming language.'

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
